/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.tiny.api.service.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.tiny.url.model.TinyUrlRequest;
import com.tiny.url.model.TinyUrlResponse;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-09-26T16:34:48.138Z")

@Api(value = "shorten-url", description = "the shorten-url API")
@RequestMapping(value = "/v1")
public interface ShortenUrlApi {

	@ApiOperation(value = "Post the lengthy url and get the tiny urls in response", nickname = "createTinyUrl", notes = "Post the lengthy url and get the tiny urls in response", response = TinyUrlResponse.class, tags = {
			"tiny", })
	@ApiResponses(value = {
			@ApiResponse(code = 201, message = "retrieve tiny url of the api", response = TinyUrlResponse.class),
			@ApiResponse(code = 400, message = "Bad request"),
			@ApiResponse(code = 403, message = "Permission denied") })
	@RequestMapping(value = "/shorten-url", produces = { "application/json" }, method = RequestMethod.POST)
	ResponseEntity<TinyUrlResponse> createTinyUrl(
			@ApiParam(value = "TinyUrl object that needs to be added to the store") @RequestBody TinyUrlRequest body);

}
